export const SkillGRP = {
  skill_id: 'skill_id',
  skill_level: 'skill_level',
  oper_type: 'oper_type',
  mp_consume: 'mp_consume',
  cast_range: 'cast_range',
  cast_style: 'cast_style',
  hit_time: 'hit_time',
  is_magic: 'is_magic',
  ani_char: 'ani_char',
  desc: 'desc',
  icon_name: 'icon_name',
  extra_eff: 'extra_eff',
  is_ench: 'is_ench',
  ench_skill_id: 'ench_skill_id',
  hp_consume: 'hp_consume',
  UNK_0: 'UNK_0',
  UNK_1: 'UNK_1',
}
