services:
  playwright:
    platform: linux/amd64
    image: mcr.microsoft.com/playwright:v1.52.0
    working_dir: /home/pwuser
    user: pwuser
    init: true
    tty: true
    command: /bin/sh -c "npx -y playwright@1.52.0 run-server --port 3000 --host 0.0.0.0"
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.playwright.rule=Host(`playwright.workspace.com`)"
      - "traefik.http.routers.playwright.entrypoints=websecure"
      - "traefik.http.routers.playwright.tls=true"
      - "traefik.http.services.playwright.loadbalancer.server.port=3000"
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - ./.docker/selenoid/config:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
    command: -conf /etc/selenoid/browsers.json -limit 20 -retry-count 1000 -timeout 5m0s
    restart: always
    expose:
      - 4444
  selenoid-ui:
    image: aerokube/selenoid-ui
    network_mode: bridge
    depends_on:
      - selenoid
    links:
      - selenoid
    expose:
      - 8080
    command: [--selenoid-uri, http://selenoid:4444]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.selenoid.rule=Host(`selenoid.workspace.com`)"
      - "traefik.http.routers.selenoid.entrypoints=websecure"
      - "traefik.http.routers.selenoid.tls=true"
      - "traefik.http.services.selenoid.loadbalancer.server.port=8080"
