include:
  - browser/ui/docker-compose.yml
  - browser/use/docker-compose.yml

services:
  playwright:
    platform: linux/amd64
    image: mcr.microsoft.com/playwright:v1.52.0
    working_dir: /home/pwuser
    user: pwuser
    init: true
    tty: true
    command: /bin/sh -c "npx -y playwright@1.52.0 run-server --port 3000 --host 0.0.0.0"
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.playwright.rule=Host(`playwright.workspace.com`)"
      - "traefik.http.routers.playwright.entrypoints=web"
      - "traefik.http.routers.playwright.tls=false"
      - "traefik.http.services.playwright.loadbalancer.server.port=3000"
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - ./.docker/selenoid/config:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
    command: -conf /etc/selenoid/browsers.json -limit 20 -retry-count 1000 -timeout 5m0s
    restart: always
    expose:
      - 4444
  selenoid-ui:
    image: aerokube/selenoid-ui
    network_mode: bridge
    depends_on:
      - selenoid
    links:
      - selenoid
    expose:
      - 8080
    command: [--selenoid-uri, http://selenoid:4444]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.selenoid.rule=Host(`selenoid.workspace.com`)"
      - "traefik.http.routers.selenoid.entrypoints=web"
      - "traefik.http.routers.selenoid.tls=false"
      - "traefik.http.services.selenoid.loadbalancer.server.port=8080"
  browserless:
    platform: linux/amd64
    restart: always
    image: browserless/chrome
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - http://localhost:3000/
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    expose:
      - 3000
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      # - TOKEN=${BROWSER_TOKEN}
      - ALLOW_FILE_PROTOCOL=true
      - TZ=America/Sao_Paulo
      - PREBOOT_CHROME=true
      - KEEP_ALIVE=true
      - CONNECTION_TIMEOUT=86400000
      - MAX_CONCURRENT_SESSIONS=1
      - QUEUE_LENGTH=4
      - ENABLE_CORS=true
      - ENABLE_DEBUGGER=true
      - DEFAULT_IGNORE_HTTPS_ERRORS=true
      - EXIT_ON_HEALTH_FAILURE=true
      - FUNCTION_BUILT_INS=["crypto"]
      - FUNCTION_EXTERNALS=["request","fetch"]
      - FUNCTION_ENABLE_INCOGNITO_MODE=true
      - DEFAULT_STEALTH=true
      - USE_CHROME_STABLE=true
      # - PROXY_HOST=scrapoxy:8888
      # - PROXY_AUTH=${PROXY_AUTH}
      - DEFAULT_LAUNCH_ARGS=["--user-agent=${USER_AGENT}","--window-size=1920,1080","--autoplay-policy=user-gesture-required","--blink-settings=imagesEnabled=true","--disable-background-logging","--disable-background-networking","--disable-background-timer-throttling","--disable-backgrounding-occluded-windows","--disable-blink-features=AutomationControlled","--disable-breakpad","--disable-client-side-phishing-detection","--disable-component-update","--disable-dev-shm-usage","--disable-domain-reliability","--disable-features=IsolateOrigins,SitePerProcess","--disable-hang-monitor","--disable-infobars","--disable-ipc-flooding-protection","--disable-offer-store-unmasked-wallet-cards","--disable-print-preview","--disable-prompt-on-repost","--disable-setuid-sandbox","--disable-speech-api","--disk-cache-size=33554432","--enable-features=Vulkan","--headless=new","--memory-pressure-off","--no-default-browser-check","--no-experiments","--no-first-run","--no-pings","--no-zygote","--password-store=basic","--use-angle=vulkan","--use-gl=egl","--ignore-gpu-blocklist"]
      # "--proxy-server=http://${PROXY_HOST}","--proxy-auth=${PROXY_AUTH}"
    volumes:
      - browserless_data:/usr/src/app/workspace
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.browserless.rule=Host(`browserless.workspace.com`)"
      - "traefik.http.routers.browserless.entrypoints=web"
      - "traefik.http.routers.browserless.tls=false"
      - "traefik.http.services.browserless.loadbalancer.server.port=3000"
    shm_size: 2gb
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

volumes:
  browserless_data:
