services:
  flaresolverr:
    restart: always
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - TZ=America/Sao_Paulo
      - PROMETHEUS_ENABLED=true
      - PROMETHEUS_PORT=8000
    expose:
      - 8191
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - http://localhost:8191
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flaresolverr.rule=Host(`flaresolverr.workspace.com`)"
      - "traefik.http.routers.flaresolverr.entrypoints=websecure"
      - "traefik.http.routers.flaresolverr.tls=true"
      - "traefik.http.services.flaresolverr.loadbalancer.server.port=8191"
  brightdata:
    restart: always
    platform: linux/amd64
    image: luminati/luminati-proxy
    command: proxy-manager
    expose:
      - 22999
      - 24000
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - http://localhost:22999/api/proxies
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - ./.docker/brightdata:/root/proxy_manager
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.brightdata.rule=Host(`brightdata.workspace.com`)"
      - "traefik.http.routers.brightdata.entrypoints=websecure"
      - "traefik.http.routers.brightdata.tls=true"
      - "traefik.http.services.brightdata.loadbalancer.server.port=22999"
  scrapoxy:
    restart: always
    image: scrapoxy/scrapoxy
    environment:
      - AUTH_LOCAL_USERNAME=${AUTH_LOCAL_USERNAME}
      - AUTH_LOCAL_PASSWORD=${AUTH_LOCAL_PASSWORD}
      - BACKEND_JWT_SECRET=${BACKEND_JWT_SECRET}
      - FRONTEND_JWT_SECRET=${FRONTEND_JWT_SECRET}
      - STORAGE_FILE_FILENAME=/cfg/scrapoxy.json
    expose:
      - 8888
      - 8890
    volumes:
      - scrapoxy_data:/cfg
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scrapoxy.rule=Host(`scrapoxy.workspace.com`)"
      - "traefik.http.routers.scrapoxy.entrypoints=websecure"
      - "traefik.http.routers.scrapoxy.tls=true"
      - "traefik.http.services.scrapoxy.loadbalancer.server.port=8890"

volumes:
  scrapoxy_data:
