services:
  nodejs:
    restart: unless-stopped
    build:
      target: dist
      dockerfile: Dockerfile
      args:
        - NGINX_VERSION=${NGINX_VERSION}
        - NODE_VERSION=${NODE_VERSION}
    working_dir: /app
    expose:
      - 80
    environment:
      - NODE_ENV=production
      - TZ=${TZ:-America/Sao_Paulo}
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:80/metrics', res => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))",
        ]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 5s
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '1'
