name: ${NAMESPACE:-workspace}

x-ollama: &service-ollama
  image: ollama/ollama:latest
  networks:
    - internal
  container_name: ollama
  restart: unless-stopped
  expose:
    - 11434/tcp
  environment:
    - OLLAMA_CONTEXT_LENGTH=8192
    - OLLAMA_FLASH_ATTENTION=1
    - OLLAMA_KV_CACHE_TYPE=q8_0
    - OLLAMA_MAX_LOADED_MODELS=2
    - VECTOR_STORE_PATH=/app/vector_store
    - NVIDIA_VISIBLE_DEVICES=all
  volumes:
    - ollama_storage:/root/.ollama
  healthcheck:
    test: ['CMD', 'curl', '-f', 'http://localhost:11434']
    interval: 10s
    timeout: 5s
    retries: 5

x-init-ollama: &init-ollama
  image: ollama/ollama:latest
  networks:
    - internal
  container_name: ollama-pull-llama
  volumes:
    - ollama_storage:/root/.ollama
  entrypoint: /bin/sh
  command:
    - '-c'
    - >
      set -e;
      sleep 3;
      OLLAMA_HOST=ollama:11434 ollama pull qwen2.5:7b-instruct-q4_K_M &&
      OLLAMA_HOST=ollama:11434 ollama pull all-minilm:l6-v2 &&
      OLLAMA_HOST=ollama:11434 ollama pull nomic-embed-text

x-n8n: &service-n8n
  image: n8nio/n8n:latest
  networks: ['internal']
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    - DB_POSTGRESDB_DATABASE=n8n
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
    - N8N_USER_MANAGEMENT_DISABLED=false
    - N8N_SECURE_COOKIE=false
    - N8N_USER_MANAGEMENT_JWT_SECRET=${N8N_USER_MANAGEMENT_JWT_SECRET}
    - N8N_DEFAULT_USER_EMAIL=${N8N_DEFAULT_USER_EMAIL}
    - N8N_DEFAULT_USER_PASSWORD=${N8N_DEFAULT_USER_PASSWORD}
    - N8N_BASIC_AUTH_ACTIVE=false
    - N8N_HOST=n8n.workspace.com
    - N8N_PORT=5678
    - WEBHOOK_URL=${N8N_HOSTNAME:+https://}${N8N_HOSTNAME:-http://n8n.workspace.com}
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.n8n.rule=Host(`n8n.workspace.com`)"
    - "traefik.http.routers.n8n.service=n8n"
    - "traefik.http.routers.n8n.entrypoints=web"
    - "traefik.http.services.n8n.loadbalancer.server.port=5678"
  depends_on:
    postgres:
      condition: service_healthy

services:

  ollama-cpu:
    profiles: ['cpu']
    <<: *service-ollama

  ollama-gpu:
    profiles: ['gpu-nvidia']
    <<: *service-ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama-gpu-amd:
    profiles: ['gpu-amd']
    <<: *service-ollama
    image: ollama/ollama:rocm
    networks:
      - internal
    devices:
      - '/dev/kfd'
      - '/dev/dri'

  ollama-pull-llama-cpu:
    profiles: ['cpu']
    <<: *init-ollama
    depends_on:
      - ollama-cpu

  ollama-pull-llama-gpu:
    profiles: ['gpu-nvidia']
    <<: *init-ollama
    depends_on:
      - ollama-gpu

  ollama-pull-llama-gpu-amd:
    profiles: [gpu-amd]
    <<: *init-ollama
    image: ollama/ollama:rocm
    networks:
      - internal
    depends_on:
      - ollama-gpu-amd
  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui
    runtime: nvidia
    expose:
      - 8080/tcp
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - openwebui_data:/app/backend/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.open-webui.rule=Host(`open-webui.workspace.com`)"
      - "traefik.http.routers.open-webui.service=open-webui"
      - "traefik.http.routers.open-webui.entrypoints=web"
      - "traefik.http.services.open-webui.loadbalancer.server.port=8080"
    networks:
      - internal
    deploy:
      restart_policy:
        condition: always
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  traefik:
    image: traefik
    container_name: traefik
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --metrics.prometheus=true
      - --metrics.prometheus.buckets=0.1,0.3,1.2,5.0
      - --providers.docker=true
      - --providers.docker.watch
      - --providers.docker.exposedbydefault=false
      - --api.dashboard=true
      - --certificatesresolvers.selfsigned.acme.tlschallenge=false
      - --log.level=INFO
      - --accesslog=true
      - --providers.file.filename=/etc/traefik/tls.yml
    ports:
      - 80:80
      - 443:443
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .docker/traefik/config.yaml:/etc/traefik/traefik.yaml:ro
      - .docker/traefik/certs:/certs:ro
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: Host(`dashboard.workspace.com`)
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.entrypoints: web
      traefik.http.services.traefik.loadbalancer.server.port: 8080
    logging:
      options:
        max-size: '10m'
        max-file: '3'
  n8n-import:
    <<: *service-n8n
    container_name: n8n-import
    entrypoint: /bin/sh
    command:
      - '-c'
      - >
        n8n import:credentials --separate --input=/backup/credentials &&
        n8n import:workflow --separate --input=/backup/workflows
    volumes:
      - ./.docker/n8n/backup:/backup:ro

  n8n:
    <<: *service-n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
      - ./vendors/local-ai-packaged/n8n/backup:/backup
      - ./.docker/n8n/shared:/data/shared
    depends_on:
      n8n-import:
        condition: service_completed_successfully
    networks:
      - internal
  flowise:
    image: flowiseai/flowise
    networks:
      - internal
    restart: unless-stopped
    container_name: flowise
    expose:
      - 3001/tcp
    environment:
      - PORT=3001
      - FLOWISE_USERNAME=${FLOWISE_USERNAME}
      - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flowise.rule=Host(`flowise.workspace.com`)"
      - "traefik.http.routers.flowise.service=flowise"
      - "traefik.http.routers.flowise.entrypoints=web"
      - "traefik.http.services.flowise.loadbalancer.server.port=3001"
    volumes:
      - flowise_data:/root/.flowise
    entrypoint: /bin/sh -c "sleep 3; flowise start"
  postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
    restart: unless-stopped
    user: postgres
    environment:
      TZ: America/Sao_Paulo
      PGUSER: ${POSTGRES_USER}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 2s
      timeout: 5s
      retries: 10
    networks:
      - internal
    expose:
      - 5432/tcp
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - .docker/postgres/sws/:/docker-entrypoint-initdb.d/:ro
  redis:
    platform: linux/amd64
    image: redislabs/rejson:2.0.6
    command: redis-server --loadmodule /usr/lib/redis/modules/rejson.so --loadmodule /usr/lib/redis/modules/redisearch.so --appendonly yes --maxclients 10000 --timeout 0 --tcp-keepalive 300 --save
    environment:
      - TZ=America/Sao_Paulo
      - REDISTIMESERIES_ARGS="RETENTION_POLICY=20"
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 3s
      timeout: 10s
      retries: 10
    volumes:
      - redis_data:/data
    expose:
      - 6379/tcp
    ports:
      - 6379:6379
    networks:
      - internal
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '1'
  mysql:
    restart: unless-stopped
    image: mysql/mysql-server:${MYSQL_VERSION}
    command: ['--default-authentication-plugin', 'mysql_native_password']
    pid: host
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./.docker/mysql/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/init:/docker-entrypoint-initdb.d/
    networks:
      - internal
  mongo:
    platform: linux/amd64
    image: mongo:4
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    healthcheck:
      test: echo $(mongo --eval 'db.runCommand("ping").ok')
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - mongodb_data:/data/db
    networks:
      - internal
  pgvector:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    environment:
      TZ: America/Sao_Paulo
      PGUSER: ${PGVECTOR_USER}
      POSTGRES_USER: ${PGVECTOR_USER}
      POSTGRES_PASSWORD: ${PGVECTOR_PASSWORD}
      POSTGRES_DB: ${PGVECTOR_DATABASE}
    ports:
      - "5433:5432"
    expose:
      - 5432
    networks:
      - internal
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./.docker/postgres/pgvector/:/docker-entrypoint-initdb.d/:ro
  pinecone:
    image: ghcr.io/pinecone-io/pinecone-local:latest
    container_name: pinecone
    expose:
      - 5081
    environment:
      - PORT=5081
      - PINECONE_HOST=${PINECONE_HOST:-localhost}
      - PINECONE_API_KEY=${PINECONE_API_KEY:-apilocal}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT:-us-east1-gcp}
    networks:
      - internal
    volumes:
      - pinecone_data:/root/.pinecone
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - QDRANT__GPU__INDEXING=true
      - EMBEDDING_PROVIDER=${EMBEDDING_PROVIDER:-fastembed}
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - '6333:6333'
    expose:
      - 6333
    restart: unless-stopped
    networks:
      - internal
    healthcheck:
      test:
        - CMD-SHELL
        - bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  internal:
    driver: bridge

volumes:
  n8n_data:
  ollama_storage:
  flowise_data:
  openwebui_data:
  postgres_data:
  redis_data:
  pgvector_data:
  pinecone_data:
  qdrant_data:
  mongodb_data:
