apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-connectivity
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "dev-realm.fullname" . }}
    environment: {{ .Values.environment }}
    app.kubernetes.io/managed-by: 'Helm'
  annotations:
    meta.helm.sh/release-name: '{{ .Release.Name }}'
    meta.helm.sh/release-namespace: '{{ .Release.Namespace }}'
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - {{ printf "%s-%s" .Release.Name "api" }}
          - {{ printf "%s-%s" .Release.Name "downloader" }}
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - {{ printf "%s-%s" .Release.Name "api" }}
                  - {{ printf "%s-%s" .Release.Name "downloader" }}
        - namespaceSelector: {}  # Allow traffic from all namespaces (optional)
  egress:
    - to:
        - podSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - redis
      ports:
        - protocol: TCP
          port: 6379
    - to:
        - podSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - mongodb
      ports:
        - protocol: TCP
          port: 27017
    - to:
        - podSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - postgresql
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - podSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - proxy
      ports:
        - protocol: TCP
          port: 8080
    - to:  # Allow DNS resolution
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
    - to:  # Allow outbound traffic to the internet (optional)
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
