version: '3'
services:
  redis:
    image: bitnami/redis:latest
    command: /opt/bitnami/scripts/redis/run.sh --appendonly no
    environment:
      REDIS_AOF_ENABLED: 'no'
      REDIS_DISABLE_COMMANDS: 'FLUSHDB,FLUSHALL'
      ALLOW_EMPTY_PASSWORD: 'yes'
      REDIS_PORT_NUMBER: 6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 10s
      retries: 30
      start_period: 15s
    ports:
      - '6379:6379'
    networks:
      - backend
