FROM redis:latest

# Copy the custom configuration file to the container
COPY ./docker/redis/redis.conf /etc/redis/redis.conf

# Expose the Redis port
EXPOSE 6379

# Command to run Redis with the custom configuration file
CMD ["redis-server", "/etc/redis/redis.conf"]
