services:
  l2-cdn:
    restart: always
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
      target: cdn
    volumes:
      - ./.docker/nginx/cdn.conf:/etc/nginx/nginx.conf:ro
      - ./.docker/nginx/cdn:/usr/share/nginx/cdn:ro
      - ./.tmp/nginx/cdn:/var/log/nginx
      # - ./html:/usr/share/nginx/html/
    ports:
      - '9999:80'
    networks:
      - global
  extalia-server:
    build:
      context: .
      dockerfile: ./.docker/java/jdk8-bellsoft.Dockerfile
    command: ./start_servers.sh
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=extalia
    ports:
      - 7777:7777
      - 2106:2106
      - 9014:9014
    networks:
      - global
    volumes:
      - ./extalia/server:/app:ro
    depends_on:
      mysql:
        condition: service_healthy
  l2-extalia:
    build:
      context: .
      dockerfile: ./.docker/java/jdk8-bellsoft.Dockerfile
    command: ./start_servers.sh
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=extalia
    ports:
      - 7777:7777
      - 2106:2106
      - 9014:9014
    networks:
      - global
    volumes:
      - ./extalia/server:/app:ro
  loginserver:
    build:
      context: .
      dockerfile: ./.docker/java/jdk8-bellsoft.Dockerfile
    command: java -Xmx512m -cp ".:./libs/*:./LoginServer.jar" com.extalia.loginserver.L2LoginServer
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=extalia
    ports:
      - 2106:2106
      - 9014:9014
    networks:
      - global
    volumes:
      - ./extalia/server:/app:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
  gameserver:
    build:
      context: .
      dockerfile: ./.docker/java/jdk8-bellsoft.Dockerfile
    command: java -Xmx1024m -cp ".:./libs/*:./GameServer.jar" com.extalia.gameserver.GameServer
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=extalia
    ports:
      - 7777:7777
    networks:
      - global
    volumes:
      - ./extalia/server:/app:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      loginserver:
        condition: service_started
      mysql:
        condition: service_healthy

networks:
  global:
    driver: bridge
