#!/bin/sh
set -ex
mysql -u root -p${MYSQL_ROOT_PASSWORD} ${MYSQL_DATABASE} LOAD DATA INFILE "'./${FILENAME}'" \
INTO TABLE ${TABLE_NAME}  \
FIELDS TERMINATED BY ';' \
ENCLOSED BY '"' \
LINES TERMINATED BY '\n' \
IGNORE 1 ROWS;
