apiVersion: 1

deleteDatasources:
  - name: Prometheus

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
      tlsSkipVerify: false
      timeInterval: ''
    secureJsonData: {}
  - name: InfluxDB
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    user: admin
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      dbName: influxdb
      httpMethod: GET
      tlsSkipVerify: false
      timeInterval: ''
    secureJsonData: { password: true }
