services:
  # source https://prometheus.io/docs/prometheus/latest/installation/
  prometheus:
    image: prom/prometheus:v2.45.2
    restart: always
    user: root
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus/exporter.yml:/etc/prometheus/prometheus.yml
      - ./tmp/prometheus/data:/prometheus
    networks:
      - backend

  # source https://github.com/nginxinc/nginx-prometheus-exporter
  exporter:
    image: nginx/nginx-prometheus-exporter:1.0
    restart: always
    command:
      - -nginx.scrape-uri=http://nginx/stub_status
    networks:
      - backend
    depends_on:
      - prometheus
      - nginx

  # source https://grafana.com/docs/grafana/latest/installation/docker/
  grafana:
    image: grafana/grafana:10.0.10
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./tmp/grafana/data:/var/lib/grafana
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards
      - ./docker/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./docker/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    networks:
      - backend
    depends_on:
      - prometheus
      - influxdb

  influxdb:
    image: influxdb:1.8
    restart: always
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=influxdb
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin
      - DOCKER_INFLUXDB_INIT_MODE=setup
    volumes:
      - ./docker/influxdb/config:/etc/influxdb2
      - ./tmp/influxdb/data:/var/lib/influxdb2
    networks:
      - backend

networks:
  backend:
    driver: bridge
