import { CrystalType, Material } from '@/lib/itemset'

export const CRYSTAL_TYPE: CrystalType = 's'

export const BASE_STATS = {
  chest: {
    tag: '1',
    drop_type: '0',
    drop_anim_type: '3',
    drop_radius: '4',
    drop_height: '4',
    UNK_0: '0',
    crystallizable: '1',
    UNK_1: '0',
    body_part: '10',
    armor_type: '2',
    avoid_mod: '0',
    durability: '4294967295',
    weight: '7620',
    material: 'scale_of_dragon' as Material,
    pdef: '205',
    mdef: '0',
    mpbonus: '0',
    crystal_type: CRYSTAL_TYPE,
  },
  legs: {
    tag: '1',
    drop_type: '0',
    drop_anim_type: '3',
    drop_radius: '3',
    drop_height: '4',
    UNK_0: '0',
    drop_tex: '',
    crystallizable: '1',
    UNK_1: '0',
    body_part: '11',
    armor_type: '2',
    avoid_mod: '0',
    durability: '4294967295',
    weight: '3260',
    material: 'scale_of_dragon' as Material,
    pdef: '128',
    mdef: '0',
    mpbonus: '0',
    crystal_type: CRYSTAL_TYPE,
  },
  gloves: {
    tag: '1',
    drop_type: '0',
    drop_anim_type: '3',
    drop_radius: '3',
    drop_height: '3',
    UNK_0: '0',
    drop_tex: '',
    crystallizable: '1',
    UNK_1: '0',
    body_part: '9',
    armor_type: '2',
    avoid_mod: '0',
    durability: '4294967295',
    weight: '540',
    material: 'leather' as Material,
    pdef: '55',
    mdef: '0',
    mpbonus: '0',
    crystal_type: CRYSTAL_TYPE,
  },
  feet: {
    tag: '1',
    drop_type: '0',
    drop_anim_type: '3',
    drop_radius: '2',
    drop_height: '7',
    UNK_0: '0',
    drop_tex: '',
    crystallizable: '1',
    UNK_1: '0',
    body_part: '12',
    armor_type: '2',
    avoid_mod: '0',
    durability: '4294967295',
    weight: '1110',
    material: 'leather' as Material,
    pdef: '55',
    mdef: '0',
    mpbonus: '0',
    crystal_type: CRYSTAL_TYPE,
  },
  head: {
    tag: '1',
    drop_type: '0',
    drop_anim_type: '3',
    drop_radius: '2',
    drop_height: '4',
    UNK_0: '0',
    crystallizable: '1',
    UNK_1: '0',
    body_part: '6',
    armor_type: '2',
    avoid_mod: '0',
    durability: '4294967295',
    weight: '550',
    material: 'bone' as Material,
    pdef: '83',
    mdef: '0',
    mpbonus: '0',
    crystal_type: CRYSTAL_TYPE,
  },
  lhand: {
    body_part: '8',
    weight: '1170',
    material: 'bone' as Material,
    pdef: '290',
    shield_rate: '20',
    mdef: '0',
    avoid_mod: '-8',
    crystal_type: CRYSTAL_TYPE,
  },
}
