filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message  # 👈 Campo obrigatório quando usa multiline + json
    multiline.pattern: '^\s'
    multiline.negate: false
    multiline.match: after
    processors:
      - add_docker_metadata: ~

filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.image: global-ai-context
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              json.keys_under_root: true
              json.add_error_key: true
              processors:
                - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

setup.template.name: "python-logs"
setup.template.pattern: "python-logs*"
setup.template.enabled: true
setup.ilm.enabled: false

logging.level: info
