{
 "title": "Express Prometheus Middleware",
 "description": "Official Grafana dashboard for npm package @matteodisabatino/express-prometheus-middleware",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance:",
    "query": {
     "query": "label_values(nodejs_version_info, instance)"
    }
   },
   {
    "name": "node_exporter",
    "label": "Node Exporter:",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Count by class",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    http_requests_total{instance=\"$instance\",status=~\".{1,2}\"} or\n    on() label_replace(vector(0),\"status\",\"0\",\"\",\"\")\n)",
     "legendFormat": "0xx"
    },
    {
     "expr": "sum(\n    http_requests_total{instance=\"$instance\",status=~\"1..\"} or\n    on() label_replace(vector(0),\"status\",\"100\",\"\",\"\")\n)",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum(\n    http_requests_total{instance=\"$instance\",status=~\"2..\"} or\n    on() label_replace(vector(0),\"status\",\"200\",\"\",\"\")\n)",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(\n    http_requests_total{instance=\"$instance\",status=~\"3..\"} or\n    on() label_replace(vector(0),\"status\",\"300\",\"\",\"\")\n)",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(\n    http_requests_total{instance=\"$instance\",status=~\"4..\"} or\n    on() label_replace(vector(0),\"status\",\"400\",\"\",\"\")\n)",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(\n    http_requests_total{instance=\"$instance\",status=~\"5..\"} or\n    on() label_replace(vector(0),\"status\",\"500\",\"\",\"\")\n)",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(\n    http_requests_total{instance=\"$instance\",status=~\".*\"} or\n    on() label_replace(vector(0),\"status\",\"0\",\"\",\"\")\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Request duration average by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{instance=\"$instance\"} / http_request_duration_seconds_count{instance=\"$instance\"}",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Request count by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_requests_total{instance=\"$instance\"}",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Request duration 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (job, le) (rate(http_request_duration_seconds_bucket{instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "Request duration 95th percentile"
    }
   ]
  },
  {
   "title": "Request duration 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(http_request_duration_seconds_bucket{instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "Request duration 99th percentile"
    }
   ]
  },
  {
   "title": "Request duration up to 5ms by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{instance=\"$instance\",le=\"0.005\"}",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Request duration up to 10ms by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{instance=\"$instance\",le=\"0.01\"}",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Request duration up to 25ms by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{instance=\"$instance\",le=\"0.025\"}",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Request duration up to 50ms by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{instance=\"$instance\",le=\"0.05\"}",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Request duration up to 100ms by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{instance=\"$instance\",le=\"0.1\"}",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Request duration up to 250ms by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{instance=\"$instance\",le=\"0.25\"}",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Request duration up to 500ms by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{instance=\"$instance\",le=\"0.5\"}",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Request duration up to 1s by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{instance=\"$instance\",le=\"1\"}",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Request duration up to 2.5s by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{instance=\"$instance\",le=\"2.5\"}",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Request duration up to 5s by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{instance=\"$instance\",le=\"5\"}",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Request duration up to 10s by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{instance=\"$instance\",le=\"10\"}",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Request duration up to Infinity by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{instance=\"$instance\",le=\"+Inf\"}",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Request rate - Number of requests per second"
    }
   ]
  },
  {
   "title": "4xx by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_requests_total{instance=\"$instance\",status=~\"4..\"}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "5xx by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_requests_total{instance=\"$instance\",status=~\"5..\"}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "4xx or 5xx by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_requests_total{instance=\"$instance\",status=~\"4..\"} or http_requests_total{instance=\"$instance\",status=~\"5..\"}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Instance CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((sum(process_cpu_seconds_total{instance=\"$instance\"}) - avg(rate(node_cpu_seconds_total{instance=\"$node_exporter\",mode=\"idle\"}[$__rate_interval]))) * 100) / sum(node_cpu_seconds_total{instance=\"$node_exporter\"})",
     "legendFormat": "Usage CPU percentage by service"
    }
   ]
  },
  {
   "title": "Instance RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{instance=\"$instance\"}) / sum(node_memory_MemTotal_bytes{instance=\"$node_exporter\"}) * 100",
     "legendFormat": "Percentage of RAM used by service"
    }
   ]
  },
  {
   "title": "Garbage collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of garbage collections",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 98 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(nodejs_gc_runs_total{instance=\"$instance\",gctype=\"Scavenge\"} OR on() label_replace(vector(0),\"gctype\",\"Scavenge\",\"\",\"\")) by (gctype)",
       "legendFormat": "{{gctype}}"
      },
      {
       "expr": "sum(nodejs_gc_runs_total{instance=\"$instance\",gctype=\"Mark/Sweep/Compact\"} OR on() label_replace(vector(0),\"gctype\",\"Mark/Sweep/Compact\",\"\",\"\")) by (gctype)",
       "legendFormat": "{{gctype}}"
      },
      {
       "expr": "sum(nodejs_gc_runs_total{instance=\"$instance\",gctype=\"IncrementalMarking\"} OR on() label_replace(vector(0),\"gctype\",\"IncrementalMarking\",\"\",\"\")) by (gctype)",
       "legendFormat": "{{gctype}}"
      },
      {
       "expr": "sum(nodejs_gc_runs_total{instance=\"$instance\",gctype=\"Weak/PhantomCallbackProcessing\"} OR on() label_replace(vector(0),\"gctype\",\"Weak/PhantomCallbackProcessing\",\"\",\"\")) by (gctype)",
       "legendFormat": "{{gctype}}"
      },
      {
       "expr": "sum(nodejs_gc_runs_total{instance=\"$instance\",gctype=\"All\"} OR on() label_replace(vector(0),\"gctype\",\"All\",\"\",\"\")) by (gctype)",
       "legendFormat": "{{gctype}}"
      },
      {
       "expr": "sum(nodejs_gc_runs_total{instance=\"$instance\",gctype=\"Unknown\"} OR on() label_replace(vector(0),\"gctype\",\"Unknown\",\"\",\"\")) by (gctype)",
       "legendFormat": "{{gctype}}"
      },
      {
       "expr": "sum(nodejs_gc_runs_total{instance=\"$instance\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Time the GC has been active [seconds]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_gc_duration{instance=\"$instance\"}",
       "legendFormat": "{{gctype}}"
      }
     ]
    },
    {
     "title": "Number of bytes V8 has allocated for the heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_gc_total_heap_size{instance=\"$instance\"}",
       "legendFormat": "{{gctype}}"
      }
     ]
    },
    {
     "title": "Number of bytes for compiled bytecode and JITed code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_gc_total_heap_size_executable{instance=\"$instance\"}",
       "legendFormat": "{{gctype}}"
      }
     ]
    },
    {
     "title": "Number of bytes in use by application data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_gc_used_heap_size{instance=\"$instance\"}",
       "legendFormat": "{{gctype}}"
      }
     ]
    },
    {
     "title": "The absolute limit the heap cannot exceed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_gc_heap_size_limit{instance=\"$instance\"}",
       "legendFormat": "{{gctype}}"
      }
     ]
    },
    {
     "title": "Committed size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_gc_total_physical_size{instance=\"$instance\"}",
       "legendFormat": "{{gctype}}"
      }
     ]
    },
    {
     "title": "Available heap size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_gc_total_available_size{instance=\"$instance\"}",
       "legendFormat": "{{gctype}}"
      }
     ]
    },
    {
     "title": "Current amount of memory, obtained via malloc",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_gc_malloced_memory{instance=\"$instance\"}",
       "legendFormat": "{{gctype}}"
      }
     ]
    },
    {
     "title": "Peak amount of memory, obtained via malloc",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_gc_peak_malloced_memory{instance=\"$instance\"}",
       "legendFormat": "{{gctype}}"
      }
     ]
    },
    {
     "title": "Number of the top-level contexts currently active",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_gc_number_of_native_contexts{instance=\"$instance\"}",
       "legendFormat": "{{gctype}}"
      }
     ]
    },
    {
     "title": "Number of contexts that were detached and not yet garbage collected",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_gc_number_of_detached_contexts{instance=\"$instance\"}",
       "legendFormat": "{{gctype}}"
      }
     ]
    },
    {
     "title": "Number of bytes of memory allocated outside of v8's heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_gc_external_memory{instance=\"$instance\"}",
       "legendFormat": "{{gctype}}"
      }
     ]
    },
    {
     "title": "Size of all global handles in the heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_gc_total_global_handles_size{instance=\"$instance\"}",
       "legendFormat": "{{gctype}}"
      }
     ]
    },
    {
     "title": "Size of all allocated/used global handles in the heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_gc_used_global_handles_size{instance=\"$instance\"}",
       "legendFormat": "{{gctype}}"
      }
     ]
    }
   ]
  }
 ]
}