{
 "title": "Proxy Monitor",
 "description": "Monitor proxy events and metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Errors by queue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (queue) (\r\n  count_over_time({app=\"downloader\", level=\"warn\"}[$__interval])\r\n)\r\n",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "DNS Lookup Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (hostname) (rate(dns_lookup_error_count[$__rate_interval]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Request Count by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(request_count_sum[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timeout Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (hostname) (rate(timeout_error_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Count by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(error_count[$__rate_interval]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "description": "Track active connections on proxy",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(active_connections) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}