entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/workspace.localhost.crt"
        keyFile: "/certs/workspace.localhost.key"

  certificates:
    - certFile: "/certs/workspace.localhost.crt"
      keyFile: "/certs/workspace.localhost.key"
      stores:
        - default
      domains:
        - main: "workspace.localhost"
          sans:
            - "extalia.workspace.localhost"
            - "sws.workspace.localhost"

providers:
  docker:
    exposedByDefault: false

api:
  dashboard: true

http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
