entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/workspace.com.crt"
        keyFile: "/certs/workspace.com.key"

  certificates:
    - certFile: "/certs/workspace.com.crt"
      keyFile: "/certs/workspace.com.key"
      stores:
        - default
      domains:
        - main: "workspace.com"

api:
  dashboard: true

http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

providers:
  file:
    filename: /etc/traefik/tls.yml
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: true
    defaultRule: "HostRegexp(`{{ index .Labels \"com.docker.compose.service\"}}.workspace.com`)"
