entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/workspace.com.crt"
        keyFile: "/certs/workspace.com.key"

  certificates:
    - certFile: "/certs/workspace.com.crt"
      keyFile: "/certs/workspace.com.key"
      stores:
        - default
      domains:
        - main: "workspace.com"
          sans:
            - "extalia.workspace.com"
            - "extalia-api.workspace.com"
            - "extalia-gameserver.workspace.com"
            - "sws.workspace.com"
            - "dashboard.workspace.com"

providers:
  docker:
    exposedByDefault: false

api:
  dashboard: true

http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
