services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    ports:
      - '8282:80/tcp'
    environment:
      TZ: 'America/Sao_Paulo'
    volumes:
      - './.tmp/wallos/db:/var/www/html/db'
      - './.tmp/wallos/logos:/var/www/html/images/uploads/logos'
    restart: unless-stopped
    networks:
      - internal
  rss:
    image: ghcr.io/leozqin/precis:latest
    environment:
      # make sure these match with where you're mounting volumes
      - CONFIG_DIR=/config
      - DATA_DIR=/data
      - RSS_BASE_URL=${RSS_BASE_URL-http://localhost:80}
      - PRECIS_STORAGE_HANDLER=${PRECIS_STORAGE_HANDLER-tinydb}
      # these variables depend on the handler(s) you want to use
      # you can also configure these through the UI if you want
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SLACK_API_TOKEN=${SLACK_API_TOKEN}
      # - JIRA_API_TOKEN=${JIRA_API_TOKEN}
      # - JIRA_EMAIL=${JIRA_EMAIL}
      # - NTFY_BASE_URL=${NTFY_BASE_URL}
      # - NTFY_TOPIC=${NTFY_TOPIC}

      # other variables that are unlikely to change
      - GITHUB_LINK=${GITHUB_LINK-https://github.com/mend3/workspace}
      - PRECIS_INTERNAL_PORT=${PRECIS_INTERNAL_PORT-80}
      - LLM_PROVIDER=ollama
      - OLLAMA_BASE_URL=http://ollama:11434
      - LLM_MODEL="gemma:7b-instruct"
    depends_on:
      - ollama
    ports:
      - 9003:80
    volumes:
      - ./.docker/precis/configs:/config
      - ./.docker/precis/data:/data
    networks:
      - internal
  kuma:
    image: louislam/uptime-kuma:1
    container_name: kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - kuma-data:/app/data
    networks:
      - internal
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - postgres
      - redis
    environment:
      APP_URL: 'http://localhost:3000'
      APP_SECRET: 'a783b2t4983274b92834tf73246tf327'
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
    ports:
      - "9004:3000"
    restart: unless-stopped
    volumes:
      - docmost_data:/app/data/storage
    networks:
      - internal
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace PLEASE_REPLACE_WITH_32_CHAR_CODE below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: always
    container_name: firefly_iii_cron
    env_file: ./.docker/firefly/.env
    command: sh -c " apk add tzdata && ln -s /usr/share/zoneinfo/${TZ} /etc/localtime | echo \"0 3 * * * wget -qO- http://firefly:8080/api/v1/cron/LlaqcTixcFFlN4XWUSVdWGxXzdHHLIuL;echo\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - internal
  firefly:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: ./.docker/firefly/.env
    ports:
      - 8080:8080
    depends_on:
      - mysql
    links:
      - redis
      - mysql
      - cron
    networks:
      - internal
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./.tmp/homarr/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=492bceee14479019b56ce491c1247d2a2a7c6ef17efeb988dad572645df5df8d
    ports:
      - '7575:7575'
    networks:
      - internal
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./.tmp/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    ports:
      - 8123:8123
    privileged: true
    networks:
      - internal
  jellyfin:
    image: jellyfin/jellyfin:latest # or ghcr.io/jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    volumes:
      - ./.tmp/jellyfin/config:/config
      - ./.tmp/jellyfin/cache:/cache
      - ./.tmp/jellyfin/media:/media
    networks:
      - internal
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"
      - "80:80"
      - "443:443"
    environment:
      TZ: 'America/Sao_Paulo'
      WEBPASSWORD: "us3rs3cr3t"
    volumes:
      - './.tmp/pihole/etc-pihole/:/etc/pihole/'
      - './.tmp/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: my-syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./.tmp/syncthing:/var/syncthing
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - '9001:80'
    environment:
      WORDPRESS_DB_HOST: 'mysql:3306'
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - internal
  phpbb:
    restart: always
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
      target: phpbb
    ports:
      - '9002:80'
    volumes:
      - phpbb-data:/var/www/html
    networks:
      - internal
  localstack:
    build:
      context: .
      dockerfile: ./.docker/localstack/Dockerfile
    environment:
      - SERVICES=s3
      - PERSISTENCE=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/localstack/aws:/etc/localstack/init/ready.d
    healthcheck:
      test:
        - CMD
        - curl
        - '-s'
        - localhost:4566/_localstack/init
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  wordpress-data:
  phpbb-data:
  kuma-data:
  docmost_data:
  firefly_iii_upload:
  firefly_iii_db:
