services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    environment:
      TZ: 'America/Sao_Paulo'
    volumes:
      - './.tmp/wallos/db:/var/www/html/db'
      - './.tmp/wallos/logos:/var/www/html/images/uploads/logos'
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wallos.rule=Host(`wallos.workspace.com`)"
      - "traefik.http.routers.wallos.entrypoints=web"
  rss:
    image: ghcr.io/leozqin/precis:latest
    environment:
      # make sure these match with where you're mounting volumes
      - CONFIG_DIR=/config
      - DATA_DIR=/data
      - RSS_BASE_URL=${RSS_BASE_URL-http://localhost:80}
      - PRECIS_STORAGE_HANDLER=${PRECIS_STORAGE_HANDLER-tinydb}
      # these variables depend on the handler(s) you want to use
      # you can also configure these through the UI if you want
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SLACK_API_TOKEN=${SLACK_API_TOKEN}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
      - JIRA_EMAIL=${JIRA_EMAIL}
      - NTFY_BASE_URL=${NTFY_BASE_URL}
      - NTFY_TOPIC=${NTFY_TOPIC}
      - PRECIS_INTERNAL_PORT=80
      - LLM_PROVIDER=ollama
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - LLM_MODEL="qwen2.5:7b-instruct-q4_K_M"
    volumes:
      - ./.docker/precis/configs:/config
      - ./.docker/precis/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rss.rule=Host(`rss.workspace.com`)"
      - "traefik.http.routers.rss.entrypoints=web"
  kuma:
    image: louislam/uptime-kuma:1
    container_name: kuma
    restart: always
    volumes:
      - kuma-data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kuma.rule=Host(`kuma.workspace.com`)"
      - "traefik.http.routers.kuma.service=kuma"
      - "traefik.http.routers.kuma.entrypoints=web"
      - "traefik.http.services.kuma.loadbalancer.server.port=3001"
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - postgres
      - redis
    environment:
      APP_URL: 'http://localhost:3000'
      APP_SECRET: 'a783b2t4983274b92834tf73246tf327'
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
    restart: unless-stopped
    volumes:
      - docmost_data:/app/data/storage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docmost.rule=Host(`docmost.workspace.com`)"
      - "traefik.http.routers.docmost.service=docmost"
      - "traefik.http.routers.docmost.entrypoints=web"
      - "traefik.http.services.docmost.loadbalancer.server.port=3000"
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace PLEASE_REPLACE_WITH_32_CHAR_CODE below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: always
    container_name: firefly-cron
    env_file: ./.docker/firefly/.env
    command: sh -c " apk add tzdata && ln -s /usr/share/zoneinfo/${TZ} /etc/localtime | echo \"0 3 * * * wget -qO- http://firefly:8080/api/v1/cron/LlaqcTixcFFlN4XWUSVdWGxXzdHHLIuL;echo\" | crontab - && crond -f -L /dev/stdout"
  firefly:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: ./.docker/firefly/.env
    links:
      - redis
      - mysql
      - postgres
      - cron
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firefly.rule=Host(`firefly.workspace.com`)"
      - "traefik.http.routers.firefly.service=firefly"
      - "traefik.http.routers.firefly.entrypoints=web"
      - "traefik.http.services.firefly.loadbalancer.server.port=8080"
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.tmp/homarr/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homarr.rule=Host(`homarr.workspace.com`)"
      - "traefik.http.routers.homarr.service=homarr"
      - "traefik.http.routers.homarr.entrypoints=web"
      - "traefik.http.services.homarr.loadbalancer.server.port=7575"
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./.tmp/homeassistant:/config
      - ./.docker/homeassistant/config.yaml:/config/configuration.yaml
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.home.rule=Host(`home.workspace.com`)"
      - "traefik.http.routers.home.service=home"
      - "traefik.http.routers.home.entrypoints=web"
      - "traefik.http.services.home.loadbalancer.server.port=8123"
  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: 'mysql:3306'
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress-data:/var/www/html
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress-http.rule=Host(`wordpress.workspace.com`)"
      - "traefik.http.routers.wordpress-http.entrypoints=web"
      - "traefik.http.routers.wordpress-https.rule=Host(`wordpress.workspace.com`)"
      - "traefik.http.routers.wordpress-https.entrypoints=websecure"
      - "traefik.http.routers.wordpress-https.tls=true"
    depends_on:
      - mysql
  phpbb:
    restart: always
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
      target: phpbb
    volumes:
      - phpbb-data:/var/www/html
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpbb-http.rule=Host(`phpbb.workspace.com`)"
      - "traefik.http.routers.phpbb-http.entrypoints=web"
      - "traefik.http.routers.phpbb-https.rule=Host(`phpbb.workspace.com`)"
      - "traefik.http.routers.phpbb-https.entrypoints=websecure"
      - "traefik.http.routers.phpbb-https.tls=true"
    depends_on:
      - mysql

volumes:
  wordpress-data:
  phpbb-data:
  kuma-data:
  docmost_data:
  firefly_iii_upload:
