services:
  ai-context:
    platform: linux/amd64
    container_name: ai-context
    working_dir: /app
    build:
      context: .
      dockerfile: .docker/python3/Dockerfile
      args:
        - VECTOR_TOOL=vector_generator
    command: python -m shared.python.generators.vector_from_files --root ${AI_ROOT_DIR:-.} --store qdrant --collection workspace_embedding --ignore-dirs "vendors,dist,build,.artifacts,tmp,__pycache__,node_modules,tests,__tests__,*_ignore" --ignore-files "package-lock.json,yarn.lock,pnpm-lock.yaml"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - EMBEDDING_PROVIDER=${EMBEDDING_PROVIDER}
      - QDRANT_URL=${QDRANT_URL:-http://qdrant:6333}
    volumes:
      - .:/app
    labels:
      logging: 'enabled'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    depends_on:
      qdrant:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  waha:
    restart: always
    # https://waha.devlike.pro/docs/how-to/engines/#docker-images
    # https://portal.devlike.pro/docker-image
    image: devlikeapro/waha:latest
    # Add "dns" if you have a problem with resolving "web.whatsapp.com"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    env_file:
      - .docker/waha/.env
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '10'
    expose:
      - 3000
    volumes:
      # Store sessions in the .sessions folder (comment it if you're using MongoDB)
      - '.docker/waha/sessions:/app/.sessions'
      # Save media files
      # https://waha.devlike.pro/docs/how-to/storages/#save-media-files-between-the-container-restarts
      - '.docker/waha/media:/app/.media'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.waha.rule=Host(`waha.workspace.com`)"
      - "traefik.http.routers.waha.entrypoints=web"
      - "traefik.http.services.waha.loadbalancer.server.port=3000"
  rss:
    container_name: homelab-rss
    image: ghcr.io/leozqin/precis:latest
    environment:
      - CONFIG_DIR=/config
      - DATA_DIR=/data
      - RSS_BASE_URL=${RSS_BASE_URL-http://localhost:80}
      - PRECIS_STORAGE_HANDLER=${PRECIS_STORAGE_HANDLER-tinydb}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SLACK_API_TOKEN=${SLACK_API_TOKEN}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
      - JIRA_EMAIL=${JIRA_EMAIL}
      - NTFY_BASE_URL=${NTFY_BASE_URL}
      - NTFY_TOPIC=${NTFY_TOPIC}
      - PRECIS_INTERNAL_PORT=80
      - LLM_PROVIDER=ollama
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - LLM_MODEL="qwen2.5:7b-instruct-q4_K_M"
    volumes:
      - ./.docker/precis/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rss.rule=Host(`rss.workspace.com`)"
      - "traefik.http.routers.rss.entrypoints=web"
  kuma:
    container_name: homelab-kuma
    image: louislam/uptime-kuma:1
    restart: always
    volumes:
      - kuma-data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kuma.rule=Host(`kuma.workspace.com`)"
      - "traefik.http.routers.kuma.service=kuma"
      - "traefik.http.routers.kuma.entrypoints=web"
      - "traefik.http.services.kuma.loadbalancer.server.port=3001"
  docmost:
    container_name: homelab-docmost
    image: docmost/docmost:latest
    depends_on:
      - postgres
      - redis
    environment:
      APP_URL: 'http://localhost:3000'
      APP_SECRET: 'a783b2t4983274b92834tf73246tf327'
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
    restart: unless-stopped
    volumes:
      - docmost_data:/app/data/storage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docmost.rule=Host(`docmost.workspace.com`)"
      - "traefik.http.routers.docmost.service=docmost"
      - "traefik.http.routers.docmost.entrypoints=web"
      - "traefik.http.services.docmost.loadbalancer.server.port=3000"
  cron:
    container_name: homelab-firefly-cron
    image: alpine
    restart: always
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace PLEASE_REPLACE_WITH_32_CHAR_CODE below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    env_file: ./.docker/firefly/.env
    command: sh -c " apk add tzdata && ln -s /usr/share/zoneinfo/${TZ} /etc/localtime | echo \"0 3 * * * wget -qO- http://firefly:8080/api/v1/cron/LlaqcTixcFFlN4XWUSVdWGxXzdHHLIuL;echo\" | crontab - && crond -f -L /dev/stdout"
  firefly:
    container_name: homelab-firefly
    image: fireflyiii/core:latest
    hostname: app
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: ./.docker/firefly/.env
    links:
      - redis
      - mysql
      - postgres
      - cron
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firefly.rule=Host(`firefly.workspace.com`)"
      - "traefik.http.routers.firefly.service=firefly"
      - "traefik.http.routers.firefly.entrypoints=web"
      - "traefik.http.services.firefly.loadbalancer.server.port=8080"
  homarr:
    container_name: homelab-homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.tmp/homarr/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homarr.rule=Host(`homarr.workspace.com`)"
      - "traefik.http.routers.homarr.service=homarr"
      - "traefik.http.routers.homarr.entrypoints=web"
      - "traefik.http.services.homarr.loadbalancer.server.port=7575"
  homeassistant:
    container_name: homelab-homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./.tmp/homeassistant:/config
      - ./.docker/homeassistant/config.yaml:/config/configuration.yaml
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.home.rule=Host(`home.workspace.com`)"
      - "traefik.http.routers.home.service=home"
      - "traefik.http.routers.home.entrypoints=web"
      - "traefik.http.services.home.loadbalancer.server.port=8123"
  wordpress:
    container_name: homelab-wordpress
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: 'mysql:3306'
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress-data:/var/www/html
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.workspace.com`)"
      - "traefik.http.routers.wordpress.service=wordpress"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    depends_on:
      - mysql
  phpbb:
    restart: always
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
      target: phpbb
    volumes:
      - phpbb-data:/var/www/html
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpbb-http.rule=Host(`phpbb.workspace.com`)"
      - "traefik.http.routers.phpbb-http.entrypoints=web"
      - "traefik.http.routers.phpbb-https.rule=Host(`phpbb.workspace.com`)"
      - "traefik.http.routers.phpbb-https.entrypoints=websecure"
      - "traefik.http.routers.phpbb-https.tls=true"
    depends_on:
      - mysql

volumes:
  wordpress-data:
  phpbb-data:
  kuma-data:
  docmost_data:
  firefly_iii_upload:
