services:
  pgvector:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    environment:
      TZ: America/Sao_Paulo
      PGUSER: ${PGVECTOR_USER}
      POSTGRES_USER: ${PGVECTOR_USER}
      POSTGRES_PASSWORD: ${PGVECTOR_PASSWORD}
      POSTGRES_DB: ${PGVECTOR_DATABASE}
    expose:
      - 5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./.docker/pgvector/:/docker-entrypoint-initdb.d/:ro
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - QDRANT__GPU__INDEXING=true
      - EMBEDDING_PROVIDER=${EMBEDDING_PROVIDER}
    volumes:
      - qdrant_data:/qdrant/storage
    expose:
      - 6333
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qdrant.rule=Host(`qdrant.workspace.com`)"
      - "traefik.http.routers.qdrant.service=qdrant"
      - "traefik.http.routers.qdrant.entrypoints=web"
      - "traefik.http.services.qdrant.loadbalancer.server.port=6333"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  pgvector_data:
  qdrant_data:
