services:
  extalia-cdn:
    restart: always
    working_dir: /usr/share/nginx/cdn
    image: nginx:${NGINX_VERSION}-alpine
    volumes:
      - ./.docker/nginx/cdn.conf:/etc/nginx/nginx.conf:ro
      - ./.docker/nginx/cdn:/usr/share/nginx/cdn:ro
    expose:
      - 80
    ports:
      - '9999:80'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cdn.rule=Host(`cdn.workspace.com`)"
      - "traefik.http.routers.cdn.entrypoints=websecure"
      - "traefik.http.routers.cdn.tls=true"
      - "traefik.http.services.cdn.loadbalancer.server.port=80"
  nprotect:
    container_name: nprotect
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
      target: base
    expose:
      - 80
    volumes:
      - ./deployment/extalia/nProtect:/var/www/html
    working_dir: /var/www/html
    environment:
      DB_HOST: mysql
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_NAME: nProtect
    depends_on:
      - mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nprotect.rule=Host(`nprotect.workspace.com`)"
      - "traefik.http.routers.nprotect.entrypoints=websecure"
      - "traefik.http.routers.nprotect.tls=true"
      - "traefik.http.services.nprotect.loadbalancer.server.port=80"
  l2j-server:
    build:
      context: .
      dockerfile: ./.docker/java/jdk8-bellsoft.Dockerfile
    command: ./start_servers.sh
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=extalia
      - GAME_SERVER_LOGIN_HOST=localhost
    expose:
      - 7777
      - 2106
      - 9014
    volumes:
      - ./deployment/extalia/server:/app
    links:
      - nprotect
    depends_on:
      mysql:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.l2j.rule=Host(`l2j.workspace.com`)"
      - "traefik.http.routers.l2j.entrypoints=websecure"
      - "traefik.http.routers.l2j.tls=true"
      - "traefik.http.services.l2j.loadbalancer.server.port=80"
  loginserver:
    build:
      context: .
      dockerfile: ./.docker/java/jdk8-bellsoft.Dockerfile
    command: java -Xmx512m -cp ".:./libs/*:./LoginServer.jar" com.extalia.loginserver.L2LoginServer
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=extalia
    expose:
      - 2106
      - 9014
    volumes:
      - ./deployment/extalia/server:/app
    depends_on:
      mysql:
        condition: service_healthy
  gameserver:
    build:
      context: .
      dockerfile: ./.docker/java/jdk8-bellsoft.Dockerfile
    command: java -Xmx1024m -cp ".:./libs/*:./GameServer.jar" com.extalia.gameserver.L2GameServer
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=extalia
      - GAME_SERVER_LOGIN_HOST=loginserver
    expose:
      - 7777
    volumes:
      - ./deployment/extalia/server:/app
    depends_on:
      loginserver:
        condition: service_started
      mysql:
        condition: service_healthy
