export const ItemName = {
  id: 'id',
  name: 'name',
  add_name: 'add_name',
  description: 'description',
  popup: 'popup',
  set_ids: 'set_ids',
  set_bonus_desc: 'set_bonus_desc',
  set_extra_id: 'set_extra_id',
  set_extra_desc: 'set_extra_desc',
  'unk[0]': 'unk[0]',
  'unk[1]': 'unk[1]',
  special_enchant_amount: 'special_enchant_amount',
  special_enchant_desc: 'special_enchant_desc',
}
